
language: node_js

node_js:
 - "0.10.28"

branches:
 only:
  - master

before_install:
 - npm install -g hexo

install:
 - npm install

script:
 - hexo generate

deploy:
 provider: s3
 access_key_id: "AKIAJI2E4OJNJ5V5DGJQ"
 secret_access_key: "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"
 bucket: "hexowebapp"
 skip_cleanup: true
 local-dir: public
 on:
  branch: master
